spring:
  application:
    name: auth-service
# 서버 포트 19095으로 설정
server:
  port: 19095
# eureka client 로 등록
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
# Jwt secret-key 등록
service:
  jwt:
    # 인증 유효 시간 1시간으로 설정
    access-expiration: 3600000
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
# dev 프로필 설정
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/msa_exam
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# prod 프로필 설정
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://endpoint:3306/msa_exam
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true